INSERT INTO options (poll_id, description) VALUES (1, 'Purebread');
INSERT INTO options (poll_id, description) VALUES (1, 'Thierry Alberni');
INSERT INTO options (poll_id, description) VALUES (1, 'Breka Bakery & Cafe');
INSERT INTO options (poll_id, description) VALUES (2, 'Action');
INSERT INTO options (poll_id, description) VALUES (2, 'Romance');
INSERT INTO options (poll_id, description) VALUES (2, 'Comedy');
INSERT INTO options (poll_id, description) VALUES (2, 'Drama');
INSERT INTO options (poll_id, description) VALUES (3, 'Theme Party');
INSERT INTO options (poll_id, description) VALUES (3, 'Night on the town');
INSERT INTO options (poll_id, description) VALUES (3, 'Simply dinner');
INSERT INTO options (poll_id, description) VALUES (3, 'A glam photoshoot');
INSERT INTO options (poll_id, description) VALUES (3, 'Treasure hunt');
INSERT INTO options (poll_id, description) VALUES (4, 'Chicken and Mushroom Pasta');
INSERT INTO options (poll_id, description) VALUES (4, 'Garlic Butter Salmon');
INSERT INTO options (poll_id, description) VALUES (4, 'Beef and Broccoli Noodle Stir-Fry');
INSERT INTO options (poll_id, description) VALUES (4, 'Honey Chili Chicken With Veggies');
INSERT INTO options (poll_id, description) VALUES (5, 'Porteau Cove Provincial Park');
INSERT INTO options (poll_id, description) VALUES (5, 'Sunnyside Campground');
INSERT INTO options (poll_id, description) VALUES (5, 'Alice Lake Provincial Park');
INSERT INTO options (poll_id, description) VALUES (6, 'Bellagio Las Vegas');
INSERT INTO options (poll_id, description) VALUES (6, 'The Venetian Resort');
INSERT INTO options (poll_id, description) VALUES (6, 'Vdara Hotel & Spa');
INSERT INTO options (poll_id, description) VALUES (6, 'ARIA Resort & Casino');
INSERT INTO options (poll_id, description) VALUES (6, 'Caesars Palace');
INSERT INTO options (poll_id, description) VALUES (6, 'The Mirage Hotel & Casino');
INSERT INTO options (poll_id, description) VALUES (7, 'Kansas City Chiefs');
INSERT INTO options (poll_id, description) VALUES (7, 'Philadelphia Eagles');
INSERT INTO options (poll_id, description) VALUES (7, 'San Francisco 49ers');
INSERT INTO options (poll_id, description) VALUES (7, 'Cincinnati Bengals');
INSERT INTO options (poll_id, description) VALUES (8, 'Chocolate');
INSERT INTO options (poll_id, description) VALUES (8, 'Vanilla');
INSERT INTO options (poll_id, description) VALUES (9, 'PS5');
INSERT INTO options (poll_id, description) VALUES (9, 'Xbox SERIES X');
INSERT INTO options (poll_id, description) VALUES (9, 'Nintendo Switch');
INSERT INTO options (poll_id, description) VALUES (9, 'Gameboy Color');
INSERT INTO options (poll_id, description) VALUES (10, 'Fly');
INSERT INTO options (poll_id, description) VALUES (10, 'Drive');
